sudo: required
services:
  - docker

before_install:
  - docker build -t shivank22/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shivank22/react-test npm test

after_success:
  - docker build -t shivank22/multi-client ./client
  - docker build -t shivank22/multi-nginx ./nginx
  - docker build -t shivank22/multi-server ./server
  - docker build -t shivank22/multi-worker ./worker